### ISSUE TITLE
is this a GUI for the homebrew version of the gaming toolkit?

### ISSUE THREAD

**Issue by Patt92** [ohaiibuzzle/Harbor#20]
Sorry for that dumb question, but it is not mentioned in the Readme, but I have to use the brew install and then can use it to manage bottles and easy launching?
From the looks of the size and not adding the toolkit to the app or at least linking, I think so.

It works pretty good, but I came to this question.

**Comment by ohaiibuzzle** [comment]
Yep, it is basically a wrapper for the brew version of the GPTk (with some QoL features, as I use an M1 Air and couldn't stand how long it takes to compile the whole shebang)
