### ISSUE TITLE
Warcraft Reforged - Black Screen

### ISSUE THREAD

**Issue by DroofZA** [ohaiibuzzle/Harbor#22]
OS: Sonoma 14 (M2 Pro)

Steps:
1. Install Harbor
2. Add bottle / install BNET
3. Run BNET and install Warcraft Reforged
4.  Launch Game -> Black Screen
<img width="628" alt="Screenshot 2023-06-13 at 10 03 09 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/f19e95f7-8063-4c54-8384-a08c3144d80f">

Things I've tried: (suggested on forums for this issue, but are not related to Wine/Mac/Harbor specifically):

- BNET Argument `-windowmode windowed`
- Setting `seenintromovie=1` in `/Users/kennyfoord/Documents/BattleNet/drive_c/users/crossover/Documents/WarcraftIII/War3Preferences.txt `
(this removes the black screen, but gets stuck at this screen)
<img width="694" alt="Screenshot 2023-06-15 at 6 33 07 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/58bac374-708d-4e78-b54f-786ce4464f42">

- Setting Mac network to "Link-local-only"
- Disabling AV/Firewall
- Running game with BNET argument `-graphicsapi Direct3DXX` DX8, 9, 10, 11 (Change appears on Metal HUD opposite Rosetta x86_64)
<img width="252" alt="Screenshot 2023-06-16 at 5 07 35 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/766767bb-ae24-497c-8274-312df7fca5f3">
<img width="268" alt="Screenshot 2023-06-16 at 5 08 26 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/57c0896e-faa1-4172-b59c-a6fa6c2f3a5a">

- Adding BlizzardBrowser to Windows Vista/7/8/10
<img width="365" alt="Screenshot 2023-06-16 at 5 09 04 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/fd6e4490-4dca-4945-9ea5-92699de91796">

- Adding overrides for DX11 and dxgi
<img width="377" alt="Screenshot 2023-06-16 at 5 09 10 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/1274de06-2268-46a5-bae5-73fb358f929f">

Additional Troubleshooting: 
A fix that seems to work most of the time for PC users is -> Go to NVIDIA Control Panel -> set BlizzardBrowser.exe from System Default to the Nvidia Graphics Acceleration option. If that helps anyone understand the issue.

If I use the World Editor, there is no issue displaying the game.
<img width="972" alt="Screenshot 2023-06-16 at 5 21 46 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/2df91444-4418-4797-8205-397140f721a2">

Links to issue: 
https://windowsreport.com/warcraft-3-black-screen-windows-10/
https://us.forums.blizzard.com/en/warcraft3/t/warcraft-3-reforged-beta-black-screen-when-startingsolved/8679/2
https://us.forums.blizzard.com/en/warcraft3/t/changing-screen-resolution-on-mac-now-i-can-only-see-black-screen/14269
https://us.forums.blizzard.com/en/warcraft3/t/on-startup-i-get-a-black-screen-and-a-cursor-how-do-i-fix-this/15106/12
https://us.forums.blizzard.com/en/warcraft3/t/black-screen-after-newest-patch/28483/18
https://us.forums.blizzard.com/en/warcraft3/t/black-screen-in-full-screen-mood/25245/2

**Comment by ohaiibuzzle** [comment]
https://appdb.winehq.org/objectManager.php?sClass=version&iId=38407

Appears to be a known issue on Wine side, not just GPTK

**Comment by DroofZA** [comment]
I saw that but not sure how to implement, also worried it would cause D4 to not work? :)

Is it safe to use this?

```
git clone https://github.com/Frogging-Family/wine-tkg-git.git
cd wine-tkg-git.git/wine-tkg-git.git

# Edit customization.cfg, especially the following values.
# "shared_gpu_resources" is the hot new stuff that's needed.
 _LOCAL_PRESET="staging"
_shared_gpu_resources="true"
# configure for your distro
_nomakepkg_dep_resolution_distro=""
# additionally I'd suggest
_nomakepkg_prefix_path="/home/USERNAME/opt/wine-tkg"
 _EXTERNAL_INSTALL="true"

# Compiling will take some time. (about 10 minutes on a Ryzen-5800X with 16 threads)
./non-makepkg-build.sh
```

OR install this? https://github.com/GloriousEggroll/wine-ge-custom/releases

**Comment by ohaiibuzzle** [comment]
Those are based on Proton which, while it **is** Wine, have quite a few modifications that I am not sure would work on macOS
Also the version doesn't match. GPTK is Wine 7.7 and GE Proton is quite a bit newer

**Comment by ohaiibuzzle** [comment]
@DroofZA Can you try this
Update Harbor to 0.1.6-alpha
Run `rm -rf /usr/local/opt/game-porting-toolkit/lib/external`
Open Harbor, use the Safe Installer and reinstall GPTK

**Comment by DroofZA** [comment]
@ohaiibuzzle I'll try, but I only see 0.1.5 available

EDIT: Used 0.1.5 and reinstalled using Safe Installer.

Took about 5 seconds and gave me this:
```
Game Porting Toolkit installation complete. You can now close this window
exit
```

Ok so far?

EDIT EDIT: I'm stuck on a BNET update loop, if I run the game it updates for a second and nothing launches. I also have Whisky installed, will that conflict?
Is there a way to completely remove everything relating to wine/gtpx/homebrew/xcode15? I feel like this is due to duplicates or file structure issues. 

EDIT EDIT EDIT:  restarted, turned on Esync, and killed wine bottles, Warcraft ran but same issue, still stuck. Is there a way to show a log of whats happening when it gets stuck?

**Comment by ohaiibuzzle** [comment]
@DroofZA Basically I fixed some buggy behaviors of the DirectX installer in 0.1.5
You can download this app:
https://github.com/guitarfreak/DirectX-11-Demo/releases/tag/v0.6.2
And open it in your bottle. If it launches correctly (without "Failed to create D3D device") then Harbor is working as it should.

Logging can be done like this:
1. Open a terminal and run
2. `/Applications/Harbor.app/Contents/MacOS/Harbor`
3. Open the configuration page for your bottle and turn off "Don't log to stdout".
Log generated by that bottle will now appear in the terminal

**Comment by DroofZA** [comment]
The demo runs, its most likely the horror show that is Reforged...

Here is some of the log when I launch, if it helps. can give you something longer if needed.

```

01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
0b84:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0b84:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b84:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0b84:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70
0b90:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0b90:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b90:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0b90:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70
0b9c:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0b9c:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b9c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
0b9c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
0ba8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0ba8:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0ba8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0ba8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70
0bb4:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0bb4:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0bb4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0bb4:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70
0bc0:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0bc0:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0bc0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0bc0:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 2078F6D4.
01b8:fixme:dxgi:d3d11_s
```

**Comment by ohaiibuzzle** [comment]
@DroofZA GPTk has an 1.0.2 update, perhaps you can try it and see if it works
If it doesn't, use **Gcenx**'s DXVK fork, install a build from HarborBuilder that includes Vulkan and switch it on

**Comment by DroofZA** [comment]
Nope :(

This DXVK fork? https://github.com/Gcenx/DXVK-macOS/releases/tag/v1.10.3-20230507

Then installed v0.2.4-alpha -> Updated Harbor -> ran `rm -rf /usr/local/opt/game-porting-toolkit/lib/external` -> Reinstalled GPTk -> installed DXVK from above link and enabled it, I get a DLL error when running BNET.


<img width="850" alt="Screenshot 2023-07-04 at 10 18 50 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/813c1d2f-7b67-4e23-82cf-5a5727619dea">

<img width="243" alt="Screenshot 2023-07-04 at 10 18 56 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/280ce6e7-ddd0-4580-9ac6-9e7cdd5a49e0">

<img width="327" alt="Screenshot 2023-07-04 at 10 18 39 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/79c6a606-7b0a-49e3-b29b-99a7721392f2">

**Comment by ohaiibuzzle** [comment]
Turn off DXVK, then click the Update button (bottom right of the bottle details page)
That *should* sync up your bottle DLLs with Wine's

**Comment by DroofZA** [comment]
Turning off DXVK and updating seems to not do anything.

**Comment by ohaiibuzzle** [comment]
I wonder if you can just bypass Battle.net and instead just launch the game executable directly... If that is the case, try it with GPTK and DXVK and see if any of them manages to work

If one does I can make a bodge that will make both of them work

**Comment by DroofZA** [comment]
I tried that but it forces BNET to open when launching Warcraft III.exe

**Comment by ohaiibuzzle** [comment]
> I tried that but it forces BNET to open when launching Warcraft III.exe

I found a way that may work
Just open Bnet with whichever method that doesn't cause it to blackscreen, then open its settings and disable graphics acceleration in the launcher. Then it will (quite reliably) open

**Comment by DroofZA** [comment]
Not sure what you mean? Disabling the hardware acceleration still forces BNET to open when trying to launch Warcraft III.exe

EDIT: If you are referring to the DLL + DXVK issue, I can launch Warcraft III.exe with it enabled, but I get this
<img width="711" alt="Screenshot 2023-07-10 at 11 52 44 AM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/c7be0382-a395-4fe0-ad31-5a9d87d05247">

Vulcan DXVK via Whisky HUD if it helps:
<img width="611" alt="Screenshot 2023-07-10 at 12 22 18 PM" src="https://github.com/ohaiibuzzle/Harbor/assets/20288750/70af6342-0cee-451e-937c-53e24066826d">

**Comment by ohaiibuzzle** [comment]
> Not sure what you mean? Disabling the hardware acceleration still forces BNET to open when trying to launch Warcraft III.exe

Basically the idea is that since Bnet doesn't work properly with DXVK but GPTK does, you launch it in GPTK mode and then disable its graphics acceleration.
That way it doesn't try to use DX anymore so you can somewhat properly use it when you enable DXVK again

**Comment by HolimaX** [comment]
Same issue here.

System:

$ sh winetricks
wine-8.13 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.92.0
FC38

$ inxi -Gxxx
Graphics:
  Device-1: Intel DG2 [Arc A770] driver: i915 v: kernel arch: Gen-12.7 pcie:
    speed: 2.5 GT/s lanes: 1 ports: active: HDMI-A-1 empty: DP-1, DP-2, DP-3,
    DP-4, HDMI-A-2, HDMI-A-3 bus-ID: 03:00.0 chip-ID: 8086:56a0 class-ID: 0300
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.9
    compositor: gnome-shell v: 44.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x286mm (20.00x11.26")
    s-diag: 583mm (22.95")
  Monitor-1: HDMI-A-1 mapped: HDMI-1 model: BenQ G2420HDBL
    serial: RAB03454SL000 res: 1920x1080 hz: 60 dpi: 102
    size: 477x268mm (18.78x10.55") diag: 604mm (23.8") modes: max: 1920x1080
    min: 720x400
  API: OpenGL v: 4.6 Mesa 23.1.5 renderer: Mesa Intel Arc A770 Graphics
    (DG2) direct-render: Yes
