### ISSUE TITLE
Harbor crashes at launch on Sonoma Dev Beta 2

### ISSUE THREAD

**Issue by TheGrizzlyNinja** [ohaiibuzzle/Harbor#32]

**Comment by ohaiibuzzle** [comment]
Please attach the crash log when you open the app (It should be at ~/Library/Logs/DiagnosticReports in `ips`) format

**Comment by TheGrizzlyNinja** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Harbor [3930]
Path:                  /Applications/Harbor.app/Contents/MacOS/Harbor
Identifier:            dev.ohaiibuzzle.Harbor
Version:               0.2.0 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-06-21 22:59:14.9254 -0500
OS Version:            macOS 14.0 (23A5276g)
Report Version:        12
Anonymous UUID:        7676437E-E41B-F07E-D363-D6ACAE673D9B


Time Awake Since Boot: 4100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: _$s21DeveloperToolsSupport17UVPreviewRegistryCMn
Referenced from: <0947C78C-FF89-37EC-9A78-39094DC6E755> /Applications/Harbor.app/Contents/MacOS/Harbor
Expected in:     <A98CA983-1792-32D9-A19F-D196B44AC9B6> /System/Library/Frameworks/DeveloperToolsSupport.framework/Versions/A/DeveloperToolsSupport
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x18fc45b4c __abort_with_payload + 8
1   dyld                          	       0x18fc5218c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18fc521c0 abort_with_payload + 16
3   dyld                          	       0x18fbd9518 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x18fbd61e8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3884
5   dyld                          	       0x18fbd4f44 start + 1948


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016fc98d40   x3: 0x00000000000000d0
    x4: 0x000000016fc98940   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x00000000000007f0
    x8: 0x0000000000000020   x9: 0x000000016fc988aa  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000033  x13: 0x0000000000000000  x14: 0x000000025005e5f9  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x000000018fbd237c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fc98940  x21: 0x00000000000000d0  x22: 0x000000016fc98d40  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x00000001005fad80  x26: 0x0000000000000de0  x27: 0x00000001005fad80
   x28: 0x000000001f070004   fp: 0x000000016fc98910   lr: 0x000000018fc5218c
    sp: 0x000000016fc988d0   pc: 0x000000018fc45b4c cpsr: 0x80001000
   far: 0x000000010063c000  esr: 0x56000080  Address size fault

Binary Images:
       0x100164000 -        0x1001c7fff dev.ohaiibuzzle.Harbor (0.2.0) <0947c78c-ff89-37ec-9a78-39094dc6e755> /Applications/Harbor.app/Contents/MacOS/Harbor
       0x18fbcf000 -        0x18fc628ef dyld (*) <ffe1b63f-6ca0-3cc2-a058-f0bbd02d948f> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            1379K      244 
__AUTH_CONST                      22.8M      425 
__CTF                               824        1 
__DATA                            9641K      412 
__DATA_CONST                      20.6M      430 
__DATA_DIRTY                      1277K      135 
__FONT_DATA                        2352        1 
__LINKEDIT                       873.6M        2 
__OBJC_RO                         70.2M        1 
__OBJC_RW                         2143K        1 
__TEXT                           513.3M      445 
dyld private memory               4384K        4 
shared memory                       32K        1 
===========                     =======  ======= 
TOTAL                              1.5G     2105 



-----------
Full Report
-----------

{"app_name":"Harbor","timestamp":"2023-06-21 22:59:15.00 -0500","app_version":"0.2.0","slice_uuid":"0947c78c-ff89-37ec-9a78-39094dc6e755","build_version":"1","platform":1,"bundleID":"dev.ohaiibuzzle.Harbor","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A5276g)","roots_installed":0,"name":"Harbor","incident_id":"BB869F19-21E4-44DC-84AE-BFB170CA5521"}
{
  "uptime" : 4100,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,2",
  "coalitionID" : 3236,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A5276g",
    "releaseType" : "User"
  },
  "captureTime" : "2023-06-21 22:59:14.9254 -0500",
  "codeSigningMonitor" : 1,
  "incident" : "BB869F19-21E4-44DC-84AE-BFB170CA5521",
  "pid" : 3930,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-06-21 22:59:14.8959 -0500",
  "procStartAbsTime" : 98919822604,
  "procExitAbsTime" : 98920328035,
  "procName" : "Harbor",
  "procPath" : "\/Applications\/Harbor.app\/Contents\/MacOS\/Harbor",
  "bundleInfo" : {"CFBundleShortVersionString":"0.2.0","CFBundleVersion":"1","CFBundleIdentifier":"dev.ohaiibuzzle.Harbor"},
  "storeInfo" : {"deviceIdentifierForVendor":"23A88804-4F71-5BA2-ACD7-B02704D73E00","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "dev.ohaiibuzzle.Harbor",
  "crashReporterKey" : "7676437E-E41B-F07E-D363-D6ACAE673D9B",
  "codeSigningID" : "dev.ohaiibuzzle.Harbor",
  "codeSigningTeamID" : "PSAZVTU7XU",
  "codeSigningFlags" : 1644245777,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"NAEAANQAAAAQAQAAGAEAACABAAAoAQAAMAEAAEwBAAAwQYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkcsw\/pe\/AwCR\/XvBqP8PX9bAA1\/WEC2A0g=="},
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: _$s21DeveloperToolsSupport17UVPreviewRegistryCMn","Referenced from: <0947C78C-FF89-37EC-9A78-39094DC6E755> \/Applications\/Harbor.app\/Contents\/MacOS\/Harbor","Expected in:     <A98CA983-1792-32D9-A19F-D196B44AC9B6> \/System\/Library\/Frameworks\/DeveloperToolsSupport.framework\/Versions\/A\/DeveloperToolsSupport"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":74845,"threadState":{"x":[{"value":6},{"value":4},{"value":6170447168},{"value":208},{"value":6170446144},{"value":0},{"value":0},{"value":2032},{"value":32},{"value":6170445994},{"value":10},{"value":0},{"value":51},{"value":0},{"value":9932498425},{"value":32768},{"value":521},{"value":6706504572,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6170446144},{"value":208},{"value":6170447168},{"value":4},{"value":6},{"value":4301237632},{"value":3552},{"value":4301237632},{"value":520552452}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6707028364},"cpsr":{"value":2147487744},"fp":{"value":6170446096},"sp":{"value":6170446032},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6706977612,"matchesCrashFrame":1},"far":{"value":4301504512}},"frames":[{"imageOffset":486220,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":1},{"imageOffset":536972,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":1},{"imageOffset":537024,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":1},{"imageOffset":42264,"symbol":"dyld4::halt(char const*, dyld4::StructuredError const*)","symbolLocation":304,"imageIndex":1},{"imageOffset":29160,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3884,"imageIndex":1},{"imageOffset":24388,"symbol":"start","symbolLocation":1948,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4296425472,
    "CFBundleShortVersionString" : "0.2.0",
    "CFBundleIdentifier" : "dev.ohaiibuzzle.Harbor",
    "size" : 409600,
    "uuid" : "0947c78c-ff89-37ec-9a78-39094dc6e755",
    "path" : "\/Applications\/Harbor.app\/Contents\/MacOS\/Harbor",
    "name" : "Harbor",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6706491392,
    "size" : 604400,
    "uuid" : "ffe1b63f-6ca0-3cc2-a058-f0bbd02d948f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6705741824,
  "size" : 3937484800,
  "uuid" : "1a336fe5-62ae-34a6-b248-079a7ee6d1ae"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1379K      244 \n__AUTH_CONST                      22.8M      425 \n__CTF                               824        1 \n__DATA                            9641K      412 \n__DATA_CONST                      20.6M      430 \n__DATA_DIRTY                      1277K      135 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       873.6M        2 \n__OBJC_RO                         70.2M        1 \n__OBJC_RW                         2143K        1 \n__TEXT                           513.3M      445 \ndyld private memory               4384K        4 \nshared memory                       32K        1 \n===========                     =======  ======= \nTOTAL                              1.5G     2105 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "1cd397d27a0ab3668e4e20dcec1e0ee02a908005",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 250000007
    },
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 250000001
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "d0f6b534-d7c4-4f38-8e01-a0cdc99f9c3f",
      "experimentId" : "645b950d4dec7a5102737ec1",
      "deploymentId" : 500000002
    },
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    }
  ]
}
}

Model: Mac14,2, BootROM 10151.0.156.505.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1664 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Jun  2 2023 00:30:15 version 20.10.1035.0.8.7.150 FWID 01-ca1936f3
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: SanDisk 3.2Gen1
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

**Comment by ohaiibuzzle** [comment]
Ugh... okay... Apple seriously didn't just break their new fancy SwiftUI #Preview macro
https://developer.apple.com/documentation/developertoolssupport

**Comment by ohaiibuzzle** [comment]
Should be fixed in 0.2.1
