### ISSUE TITLE
bottle creation

### ISSUE THREAD

**Issue by Anatharias** [ohaiibuzzle/Harbor#46]
Hey, 
When you create a new bottle, it asks for the name and a path.
You should make it so when you give it a name, it creates a folder in the path with the given name.

Also, being able to import an existing bottle would be great
Thanks

**Comment by ohaiibuzzle** [comment]
Actually "importing" a bottle can be done by creating a new bottle pointing at an existing one's path. Harbor merely runs `winecfg /v win10` on it, which shouldn't mess anything up

Regarding creating a bottle, I have thought of changing its behavior. Maybe next major release

**Comment by ohaiibuzzle** [comment]
Finally did it. Should be "adequate" #54
