### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by natsukirei** [ohaiibuzzle/Harbor#49]
Hey guys

I am trying to get steam going and i cant figure out what i have to do, it installs and then nothing happens when u try to launch it.

**Comment by natsukirei** [comment]
i managed to get it working!

I had alot of trouble getting steam working with the guide and whisky, but with your program once i added the steam.exe to the primary application and set the path automatically, it ran no problem

**Comment by natsukirei** [comment]
id just like to say thankyou, your program did everything for me and i have no idea how but it just works, diablo works, steam works and im super happy

Please keep up the good work <3

I am wondering tho, theirs an option to update GPTK or configure , and it tells you to browse, i am not sure what to browse to so i can keep it up to date

**Comment by ohaiibuzzle** [comment]
> I am wondering tho, theirs an option to update GPTK or configure , and it tells you to browse, i am not sure what to browse to so i can keep it up to date

This is used when there is a GPTK update (it was actually implemented because recently there was an update from 1.0.0 to 1.0.2), you can use it to reinstall GPTK as needed

**Comment by natsukirei** [comment]
Hello Sorry to re-open this, im just wondering how i do the update, it says i need to point it to the GPTK libraries and i have no idea were they are

**Comment by ohaiibuzzle** [comment]
> Hello Sorry to re-open this, im just wondering how i do the update, it says i need to point it to the GPTK libraries and i have no idea were they are

You basically re-select the dmg that Apple distributed GPTk in

**Comment by natsukirei** [comment]
seems to have worked, downloaded the 1.0.2 DMG, selected it, selected update and the update window closed

I havnt tested a game yet but i do love this software, that is absolutely amazing how easy you made it and i cant afford crossover, it would be nice tho if we got a confirmation after the update saying it completed.
