### ISSUE TITLE
Steam game crashes.

### ISSUE THREAD

**Issue by lilycat** [ohaiibuzzle/Harbor#51]
Hi.
Thanks to you guys I am enjoying Diablo4 on my Mac. Thank you so much.
I mean Battle.net is working fine.

But Steam games do not work well.
Steam starts, but every game crashes as soon as it launches.
This may be unconnected to Harbor, but I am very troubled by it.😢

**Comment by ohaiibuzzle** [comment]
Some games (particularly older titles and games that have DRM/anticheat) have trouble with Wine on macOS
It is recommended that you use different bottles for each game launcher, that way you can use tools like Winetricks to apply patches to them and see if they work

Could you name a few titles that is borked?

**Comment by lilycat** [comment]
@ohaiibuzzle
I have only tried a very few old titles.

- https://store.steampowered.com/app/37600/Windosill/
- https://store.steampowered.com/app/21100/FEAR_3/

These two instantly crashed.
7days to die started up, but as you said, I couldn't play it due to loading errors in anti-cheat module.

> It is recommended that you use different bottles for each game launcher, that way you can use tools like Winetricks to apply patches to them and see if they work

I'm not very familiar with Wine yet.
There seem to be a few hacks out there, so I will try to learn about them and also try other titles.

**Comment by ohaiibuzzle** [comment]
FEAR should run considering that it is DirectX 11. I wonder if it is starting in a mode where it tries to push DirectX 9.0c which GPTK is not capable of running correctly.

**Comment by lilycat** [comment]
I haven't tried GPTK update yet, I'll give that a shot.
Also, another titles are worth a try.

I'll share the results again.
