### ISSUE TITLE
Witcher 3 script merger not loading

### ISSUE THREAD

**Issue by Stefidar** [ohaiibuzzle/Harbor#52]
Witcher 3 script merger does not load. It loads fine in Wineskin. Is there something missing from Apple Game Porting Toolikit's wine version that exists in Wineskin's wine you think? I tried Vcrun2022 but no luck. Counting on your knowledge.

**Comment by ohaiibuzzle** [comment]
Do you have a link to the specific one you are trying to use, there seems to be a few results for "ScriptMerger", CLI and GUI

The only thing Apple did was basically patching some calls to use their own libraries instead of what Crossover comes with

**Comment by Stefidar** [comment]
It needed .NET 4.8 specifically. Although I thought that wine mono was doing the same job, but I am probably mistaken.
