### ISSUE TITLE
Can not run .exe files

### ISSUE THREAD

**Issue by Stefidar** [ohaiibuzzle/Harbor#9]
When I select the game executable in the Harbor bottle window it does not run, if I select a shortcut it does.
<img width="1012" alt="ScreenShot 2023-06-13 at 11 05 08" src="https://github.com/ohaiibuzzle/Harbor/assets/136437826/0dd7ad0c-ac32-409d-b452-c3dbfacf0095">

**Comment by ohaiibuzzle** [comment]
My guess would be that the lnk file also specify some arguments to the game executable, which, by default for Harbor anyway, is blank.

**Comment by Stefidar** [comment]
No, no arguments, it's a plain link file in the same location. If I change it to the .exe it does not run. This:
<img width="1012" alt="ScreenShot 2023-06-13 at 12 28 16" src="https://github.com/ohaiibuzzle/Harbor/assets/136437826/e4a15333-225e-4030-98b9-fd75dfcf4db6">

does not run.

**Comment by ohaiibuzzle** [comment]
Hmm...
Quit Harbor, open your Terminal.app, run this command to start Harbor in Terminal
`/Applications/Harbor.app/Contents/MacOS/Harbor`
Select your bottle in Harbor, click the cogwheel icon (top right), uncheck the settings "Don't log to stdout", then start the exe.
You should see logs from Wine appearing in the Terminal. Look for any failure messages

**Comment by Stefidar** [comment]
With the witcher3.exe that does not load:

esync: up and running.
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00f8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000003753FE10
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000201FD40
0024:fixme:msvcrt:__clean_type_info_names_internal (0000000002535768) stub

**Comment by Stefidar** [comment]
And with the lnk file that loads fine:

esync: up and running.
0024:fixme:exec:SHELL_execute flags ignored: 0x00004000
00fc:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0100:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000003753FE10
00fc:err:dbghelp_msc:codeview_process_info Unknown CODEVIEW signature 00000000 in module L"d3d11"
00fc:err:dbghelp_msc:codeview_process_info Unknown CODEVIEW signature 00000000 in module L"dxgi"
00fc:fixme:win:DisableProcessWindowsGhosting : stub
010c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000005BE0FE10
0114:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0114:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0114:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0138:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0138:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0138:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0138:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0150:fixme:wbemprox:client_security_SetBlanket 00000002419BFEA0, 0000000003E8BFD0, 10, 0, (null), 3, 3, 0000000000000000, 0
0150:fixme:wbemprox:client_security_Release 00000002419BFEA0
0150:fixme:wbemprox:enum_class_object_Next timeout not supported
0114:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0114:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0114:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0180:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00000000969FFE10
00fc:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
00fc:fixme:wbemprox:client_security_SetBlanket 00000002419BFEA0, 0000000003E92E20, 10, 0, (null), 3, 3, 0000000000000000, 0
00fc:fixme:wbemprox:client_security_Release 00000002419BFEA0
00c0:fixme:imm:ImeSetActiveContext (0x378150, 0): stub
00c0:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000378150): stub
00fc:fixme:imm:ImeSetActiveContext (0x4fa3e1f0, 1): stub
00fc:fixme:imm:ImmReleaseContext (000000000001004E, 000000004FA3E1F0): stub
D3DMetal: UNSUPPORTED API: R32G32B32 texture buffers, using R32G32 instead
D3DMetal virtual HRESULT D3D11Device::QueryInterface(const IID &, LPVOID *): unsupported interface (e188335c-cb2e-4d3d-93db-dee597d9ffa6)
00fc:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
00fc:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0138:fixme:mmdevapi:SAC_GetMaxDynamicObjectCount (0000000040C5A900)->(000000008A3FF6E0)
0138:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff
0138:fixme:coreaudio:ca_channel_layout_to_channel_mask Unhandled channel 0xffffffff

**Comment by ohaiibuzzle** [comment]
Can you attach the lnk file?
This suggests that the game executable started and then stopped for no apparent reason

**Comment by Stefidar** [comment]
The lnk file works, it loads. The exe doesn't (that's the short first log).

[Witcher3.zip](https://github.com/ohaiibuzzle/Harbor/files/11733381/Witcher3.zip)

**Comment by ohaiibuzzle** [comment]
Ahh that makes sense now
Basically, `witcher3.exe` needs to have its working directory set to `C:\Witcher\bin\x64` before it runs. The `.lnk` set this, but Harbor doesn't, so when the game is launched and tried to use relative paths, it failed and quit 

<img width="574" alt="image" src="https://github.com/ohaiibuzzle/Harbor/assets/23693150/92d33df1-5a69-45fe-acb6-57e11aee2874">

**Comment by Stefidar** [comment]
OK, so I will continue running the lnk file then.

**Comment by Stefidar** [comment]
You can close this issue, with 0.1.3 .exe files are working perfectly! Thank you!
